import { Paper } from '@mui/material';
import { PrismLight } from 'react-syntax-highlighter';
import javascript from 'react-syntax-highlighter/dist/esm/languages/prism/javascript';
import prism from 'react-syntax-highlighter/dist/esm/styles/prism/prism';

// Entirely untested and generated by GPT (through my application) 😎
// Not sure if the packages are even real, but if they are they aren't installed

// I think the imports are bogus https://prismjs.com

// Also the method signature was messed up, look into fixing that 💭
// It looked like ({{ code = , }) => { ... } which is not valid JS

export const SyntaxHighlighter = ({ code }) => {
    return (<>
        <Paper elevation={3} style={{ padding: '20px' }}>
            <PrismLight language='javascript' style={prism} code={code} />
        </Paper>
    </>);
}
export default SyntaxHighlighter;