version: '3'
services:
  gpt-interface:
    image: gpt-interface-api
    build: ./gpt-interface-api
    ports:
      - "8000:8000"
    volumes:
      - ./gpt-interface-api:/app
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
  # next-frontend:
  #   # This container is not for development, but for production
  #   build: ./react-app
  #   ports:
  #     - "3000:3000"
  account-api:
    image: account-api
    build: ./account-api
    # volumes:
    #   - ./account-api:/app
    ports:
      - "8001:8000"
  account-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  project-api:
    image: project-api
    build: ./project-api
    # volumes:
    #   - ./project-api:/app
    ports:
      - "8002:8000"
  project-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - /var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  image-proxy:
    # This was made entirely by gpt
    image: image-proxy-by-gpt
    build: ./image-proxy-by-gpt
    ports:
      - "3001:3001"
