import React, { useEffect } from 'react'
import { OneComponentTemplate } from '@/components/oneComponentPageTemplate'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Button, Typography, useTheme } from '@mui/material'
import { signOut, useSession } from 'next-auth/react'
import TopBar from '@/components/TopBar'
import TopBarButton from '@/components/TopBarButton'

import SaveIcon from '@mui/icons-material/Save';
import AltRouteIcon from '@mui/icons-material/AltRoute';
import ShareIcon from '@mui/icons-material/Share';
import { SignUpCard } from '@/components/signUpCard'
import { SignInCard } from '@/components/signInCard'

//This page is saying it has random errors despite the fact that it doesn't. I don't know why.
//I think it's an IDE issue because the text is being highlighted wrong too

export default function SignIn() {
    const theme = useTheme();
    const session = useSession();

    return (<>
        <Head>
            <title>CAPSTONE</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Teko&display=swap" rel="stylesheet" />
        </Head>
        <style>
            {`
          @keyframes rotate {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(360deg);
            }
          }
          @keyframes rotate-text {
            0% { transform: rotateY(0deg); }
            25% { transform: rotateY(90deg); }
            50% { transform: rotateY(180deg); }
            75% { transform: rotateY(270deg); }
            100% { transform: rotateY(360deg); }
          }
        `}
        </style>

        <main style={{
            color: theme.palette.text.primary,
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'flex-start',
            alignItems: 'center',
            position: 'relative',
            overflow: 'hidden',
            backgroundColor: theme.palette.background.default,
        }}>


            <TopBar alternate showAccount={false} titleText={"Webbie"}>
                {/* <TopBarButton
                    Icon={SaveIcon}
                    text={"Save"}
                    // onClick={saveProject}
                    buttonIndex={1}
                /> */}
                {/* <TopBarButton
                    Icon={AltRouteIcon}
                    text={"Fork"}
                    // onClick={forkProject}
                    buttonIndex={2}
                /> */}
                {/* <TopBarButton
                    Icon={ShareIcon}
                    text={"Share"}
                    // onClick={shareProject}
                    buttonIndex={3}
                /> */}
            </TopBar>
            <div style={{
                flexGrow: 1,
                backgroundColor: "red",
                width: '100%',
                position: 'relative',
            }}>
                <div style={{
                    flexGrow: 1,
                    backgroundColor: theme.palette.background.default,
                    position: 'absolute',
                    top: 0,
                    right: "50%",
                    bottom: 0,
                    left: 0,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center',
                    overflow: 'hidden',
                    outline: "2px solid " + theme.palette.dragBar.default,
                    // outlineOffset: "-2px",
                    zIndex: 1,
                }}>
                    <div style={{
                        position: 'absolute',
                        width: '150%',
                        height: '150%',
                        backgroundSize: 'contain',
                        backgroundImage: 'url(/spiderweb.svg)',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        // backgroundColor: theme.palette.background.default,
                        animation: 'rotate 120s infinite linear',
                    }}></div>
                    <span style={{ zIndex: 2 }}>
                        <SignUpCard />
                    </span>
                </div>

                <div style={{
                    backgroundColor: theme.palette.background.paper,
                    position: 'absolute',
                    top: 0,
                    right: 0,
                    bottom: 0,
                    left: "50%",
                    zIndex: 0,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center',
                }}>
                    <SignInCard />
                </div>
            </div>
        </main >
    </>)
}
