import React, { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Button, Typography, useTheme } from '@mui/material'
import { signOut, useSession } from 'next-auth/react'

import ProjectList from '@/components/ProjectList'

export default function Home() {
    const theme = useTheme()
    const session = useSession()
    console.log(session)

    const [projects, setProjects] = React.useState([])

    useEffect(() => {
        if (session.data) {
            const getProjects = async () => {
                const response = await fetch(`${process.env.NEXT_PUBLIC_PROJECT_API_URL}/by_owner/${session.data.user.account_id}`, {
                    method: 'GET',
                    headers: {
                        "Authorization": `Bearer ${session.data.token}`
                    }
                })
                const data = await response.json()
                console.log(data)
                setProjects(data)
            }
            getProjects()
        }
    }, [session])

    return (
        <>
            <Head>
                <title>CAPSTONE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <style>
                {`
          @keyframes rotate {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(360deg);
            }
          }
        `}
            </style>
            <main style={{
                // backgroundColor: theme.palette.background.default,
                color: theme.palette.text.primary,
                minHeight: '100vh',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                gap: '2rem',
                position: 'relative',
                overflow: 'hidden',
            }}>
                <div style={{
                    position: 'absolute',
                    // top: "50%",
                    // left: "50%",
                    // transform: "translate(-50%, -50%)",
                    width: '250vw',
                    height: '250vh',
                    zIndex: -1,
                    backgroundImage: 'url(/spiderweb.svg)',
                    backgroundSize: '110vw',
                    backgroundRepeat: 'no-repeat',
                    backgroundPosition: 'center',
                    backgroundColor: theme.palette.background.default,
                    animation: 'rotate 120s infinite linear',
                }}></div>
                <ProjectList projects={projects} />
            </main>
        </>
    )
}
