import React, { useEffect, useState } from 'react'
import { PreviewComponent } from '@/components/reactPreview'
import { CodeEditor } from '@/components/codeEditor'
import { ResizableViewsHorizontal, ResizableViewsVertical } from '@/components/resizableViews'
import { SideBar } from '@/components/sideBar'
import { useTheme } from '@mui/material/styles';
import { EditorContextProvider } from '@/contexts/editor-context'
import dynamic from 'next/dynamic'

const PreviewAndTerminal = dynamic(
    () => import('@/components/previewTerminalParent'),
    { ssr: false }
)



//https://www.npmjs.com/package/@monaco-editor/react
// I don't think this applies to me, but it might vvv
//NOTE: you should be aware that this may require additional webpack plugins, like monaco-editor-webpack-plugin or it may be impossible to use in apps generated by CRA without ejecting them.

export default function Home() {
    const theme = useTheme();

    const [sidebarWidth, setSidebarWidth] = React.useState("300px");

    // const components_2 = [
    //     {
    //         slot: 0,
    //         component: <PreviewComponent />
    //     },
    //     {
    //         slot: 1,
    //         component: <Terminal />
    //     }
    // ]

    const components = [
        {
            slot: 0,
            component: <CodeEditor />
        },
        {
            slot: 1,
            component: <PreviewAndTerminal />
        }
    ]

    return (
        <EditorContextProvider>
            <div
                className='pageWrapper' // I might reuse this
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'flex-start',
                    alignItems: 'flex-start',
                    minWidth: '100vw',
                    minHeight: '100vh',
                    backgroundColor: theme.palette.background.default,
                    overflow: 'hidden',
                    position: 'relative',
                }}>
                <div
                    className='topBar'
                    style={{
                        width: '100%',
                        maxWidth: '100vw',
                        height: '50px',
                        display: 'flex',
                        flexDirection: 'row',
                        justifyContent: 'flex-start',
                        alignItems: 'center',
                        backgroundColor: theme.palette.background.default,
                    }}
                >

                </div>
                <div
                    style={{
                        display: "flex",
                        flexDirection: "row",
                        justifyContent: "flex-start",
                        alignItems: "flex-start",
                        width: "100%",
                        height: "calc(100vh - 50px)",
                    }}>
                    <SideBar sidebarWidth={sidebarWidth} setSidebarWidth={setSidebarWidth} />
                    <div style={{
                        width: `calc(100% - ${sidebarWidth})`,
                        height: '100%',
                    }}>
                        <ResizableViewsHorizontal items={components} />
                        {/* WebContainer Terminal Context */}
                        {/* Code Editor */}
                        {/* ResizableViewsVertical */}
                        {/* Preview */}
                        {/* Terminal */}
                        {/* ResizableViewsHorizontal */}
                    </div>
                </div>
            </div>
        </EditorContextProvider>
    )
}
