import React, { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Button, Typography, useTheme } from '@mui/material'
import { signOut, useSession } from 'next-auth/react'


export default function Home() {
  const theme = useTheme()
  const session = useSession()

  return (
    <>
      <Head>
        <title>CAPSTONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Teko&display=swap" rel="stylesheet" />
      </Head>
      <style>
        {`
          @keyframes rotate {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(360deg);
            }
          }
          @keyframes rotate-text {
            0% { transform: rotateY(0deg); }
            25% { transform: rotateY(90deg); }
            50% { transform: rotateY(180deg); }
            75% { transform: rotateY(270deg); }
            100% { transform: rotateY(360deg); }
          }
        `}
      </style>

      <main style={{
        color: theme.palette.text.primary,
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '2rem',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute',
          width: '250vw',
          height: '250vh',
          zIndex: -1,
          backgroundImage: 'url(/spiderweb.svg)',
          backgroundSize: '110vw',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
          backgroundColor: theme.palette.background.default,
          animation: 'rotate 120s infinite linear',
        }}></div>
        <Typography variant="h1" style={{
          fontFamily: "'Dancing Script', cursive",
          fontFamily: "'Teko', sans-serif"
        }}>
          Web
          <span style={{
            color: theme.palette.primary.main,
          }}>
            <span style={{
              display: "inline-block",
              animation: "rotate-text 8s infinite",
              transformOrigin: "50% 50%",
            }}>
              bi
            </span>
            e
          </span>
        </Typography>
        <Image src="/spider.png" width={150} height={150} alt='spider logo, but not like spiderman' />
        <Typography variant="h4">Webbie the web <span style={{ color: theme.palette.primary.main }}>IDE</span></Typography>
        <Link href="/editor"><Button variant="contained" color="primary" sx={{ borderRadius: "5px" }}>Try it out</Button></Link>
        {session.data ? <Button onClick={() => { signOut() }}>Sign Out</Button> :
          <Link href="/sign-in"><Button variant="contained" color="tertiary" sx={{ borderRadius: "5px", color: theme.palette.common.black }}>Sign In</Button></Link>}
      </main >
    </>
  )
}
