import React, { useEffect, useRef } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Button, Collapse, Divider, Typography, useTheme } from '@mui/material'
import { signOut, useSession } from 'next-auth/react'
import { Scrollbar } from 'react-scrollbars-custom'
import { useRouter } from 'next/router'
import MockEditorWindow from '@/components/MockEditorWindow'
import TechStackPanel from '@/components/TechStackPanel'
import IndexTopBar from '@/components/IndexTopBar'
import IndexTemplateButton from '@/components/IndexTemplateButton'
import FooterContactBadge from '@/components/FooterContactBadge'

import EmailIcon from '@mui/icons-material/Email';
import GitHubIcon from '@mui/icons-material/GitHub';
import LinkedInIcon from '@mui/icons-material/LinkedIn';

export default function Home() {
  const theme = useTheme()
  const session = useSession()
  const router = useRouter()

  const iconDivStyle = (isHovering = false) => {
    const hoverBG = (isHovering) => isHovering ? theme.palette.background.paper : theme.palette.background.default;
    return {
      minWidth: "50px",
      height: "50px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      color: theme.palette.text.primary,
    }
  };

  const collapseStyle = (isHovering = false) => {
    const hoverBG = (isHovering) => isHovering ? theme.palette.background.paper : theme.palette.background.default;
    return {
      color: theme.palette.text.primary,
      height: '50px',
      position: "relative",
    }
  };

  return (
    <>
      <Head>
        <title>Webbie - Web IDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* This is a really really cool trick https://css-tricks.com/emoji-as-a-favicon/ */}
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕸️</text></svg>"></link>
      </Head>
      <Scrollbar
        noScrollX
        style={{
          minHeight: '100vh',
          minWidth: '100vw',
          backgroundColor: theme.palette.background.default,
        }} >
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-start',
          alignItems: 'center',
          width: "100%",
          height: "100%",
        }}>

          <div
            id='top'
            style={{
              // backgroundColor: "#0000FF33",
              width: "100%",
              height: "100vh",
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-evenly',
              alignItems: 'center',
            }}
          >
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              backgroundColor: theme.palette.background.default,
              overflow: 'hidden',
            }}>
              <style>
                {`
                @keyframes rotate {
                  from {
                    transform: rotate(0deg);
                  }
                  to {
                    transform: rotate(360deg);
                  }
                }
                `}
              </style>
              <div style={{
                position: 'absolute',
                left: "calc(50% - 125vw)",
                top: "calc(50% - 125vh)",
                width: '250vw',
                height: '250vh',
                backgroundImage: 'url(/spiderweb.svg)',
                backgroundSize: '110vw',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
                backgroundColor: theme.palette.background.default,
                animation: 'rotate 120s infinite linear',
              }}></div>
            </div>
            {/* Top bar start ------------------------------------ */}
            <IndexTopBar />
            {/* Top bar end ------------------------------------ */}
            <div style={{
              maxWidth: '50%',
              zIndex: 1,
            }}>
              <Typography variant='h1' style={{
                fontFamily: 'Teko',
                color: theme.palette.text.primary,
                lineHeight: '5.5rem',
                width: '450px'
              }}>
                <span style={{ color: theme.palette.primary.main }}>
                  {"Develop "}
                </span>
                the web <br />
                from the
                <span style={{ color: theme.palette.primary.main }}>
                  {" web"}
                </span>
              </Typography>
              <Typography variant='h6' style={{
                color: theme.palette.text.primary,
                width: '450px',

              }}>
                Webbie is a web IDE that lets you develop and share web projects from your browser.
              </Typography>
              <Button color='secondary' variant='contained'
                onClick={() => window.location.href = "/editor/3"}
                sx={{
                  marginTop: '1rem',
                }}>
                Try the demo
              </Button>
            </div>
            {/* Mini Editor inside Mock Window */}
            <MockEditorWindow />
          </div>
          <div
            id="TechStack"
            style={{
              backgroundColor: theme.palette.background.paper,
              width: "100%",
              height: "70vh",
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-evenly',
              alignItems: 'center',
            }}>
            <TechStackPanel />
          </div>
          <div
            id="Templates"
            style={{
              width: "100%",
              height: "25vh",
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'flex-start',
              alignItems: 'center',
            }}>
            <Typography variant='h3' style={{
              color: theme.palette.text.primary,
              fontFamily: 'Teko',
              padding: '1rem',
              marginTop: "10px",
              textAlign: 'center',
            }}>
              Try one of our templates
            </Typography>
            <div style={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-evenly',
              gap: '1rem',
              width: 'calc(100% - 2rem)',
              padding: '0 1rem',
              flexGrow: 1
            }}>

              {/* set onClick to open template projects when they are made/finalized 💭 */}
              <IndexTemplateButton
                text='Node.JS'
                iconDivBackgroundImage={`url("/nodejs-icon.png")`}
                onClick={() => {
                  window.location.href = "/editor/1"
                }}
              />
              <IndexTemplateButton
                text='Express'
                iconDivBackgroundImage={`url("/transparent_express_js_icon.png")`}
                onClick={() => {
                  window.location.href = "/editor/1"
                }}
              />
              <IndexTemplateButton
                text='Basic Web'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://logos-download.com/wp-content/uploads/2017/07/HTML5_badge.png")`}
                onClick={() => {
                  window.location.href = "/editor/2"
                }}
              />
              <IndexTemplateButton
                text='React'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg")`}
                onClick={() => {
                  window.location.href = "/editor/3"
                }}
              />
              <IndexTemplateButton
                text='Next.JS'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://seekicon.com/free-icon-download/next-js_1.svg")`}
                onClick={() => {
                  window.location.href = "/editor/4"
                }}
                customButtonIconStyle={{
                  backgroundColor: "white",
                  borderRadius: '50%',
                  outline: "solid 3px black",
                  outlineOffset: "-2px",
                }} />
              <IndexTemplateButton
                text='Vue'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg")`}
                onClick={() => {
                  window.location.href = "/editor/5"
                }}
              />
              <IndexTemplateButton
                text='Angular'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg")`}
                onClick={() => {
                  window.location.href = "/editor/6"
                }}
              />
              <IndexTemplateButton
                text='Svelte'
                iconDivBackgroundImage={`url("${process.env.NEXT_PUBLIC_IMG_PROXY}https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg")`}
                onClick={() => {
                  window.location.href = "/editor/7"
                }}
              />
            </div>
          </div>
          <div
            id='Footer'
            style={{
              backgroundColor: "#130925",
              width: "100%",
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'flex-start',
              alignItems: 'center',
              padding: '1rem 2rem',
            }}>
            <div>
              <style>
                {`
          @keyframes rotate-text {
            0% { transform: rotateY(0deg); }
            25% { transform: rotateY(90deg); }
            50% { transform: rotateY(180deg); }
            75% { transform: rotateY(270deg); }
            100% { transform: rotateY(360deg); }
          }
                `}
              </style>
              <Typography variant='h3' style={{
                fontFamily: 'Teko',
                color: theme.palette.text.primary,
                marginLeft: '1rem',
              }}>
                Web
                <span style={{
                  color: theme.palette.primary.main,
                }}>
                  <span style={{
                    display: "inline-block",
                    animation: "rotate-text 8s infinite",
                    transformOrigin: "50% 50%",
                  }}>
                    bi
                  </span>
                  e
                </span>
              </Typography>
            </div>
            <Divider orientation='vertical' flexItem style={{
              marginLeft: '1rem',
              marginRight: '1rem',
              height: '50px',
              width: '1px',
              backgroundColor: theme.palette.text.primary,
            }} />
            <Typography variant='h4' color={theme.palette.text.primary} fontFamily={"Teko"} sx={{ pr: 1 }}>
              Contact:
            </Typography>
            <FooterContactBadge Icon={GitHubIcon} text='Mcbuzzerr' url='https://github.com/mcbuzzerr' />
            <FooterContactBadge Icon={LinkedInIcon} text='AlexBatesDev' url='https://www.linkedin.com/in/alexbatesdev/' />
            <FooterContactBadge Icon={EmailIcon} text='AlexBates.Dev@gmail.com' copyOnClick />
            <Typography variant='h5' color={theme.palette.primary.main} fontFamily={"Teko"} style={{
              marginLeft: 'auto',
              marginRight: '1rem',
            }}>
              Alex Bates &copy; {new Date().getFullYear()}
            </Typography>
          </div>
        </div>
      </Scrollbar >

    </>
  )
}
