import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { ConversationWindow } from '@/components/conversationWindow'

export default function Home() {
  return (
    <>
      <Head>
        <title>CAPSTONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ConversationWindow />
      </main>
    </>
  )
}
