import React, { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Button, Collapse, Typography, useTheme } from '@mui/material'
import { signOut, useSession } from 'next-auth/react'
import { AccountCircle, Close, Fullscreen, Minimize } from '@mui/icons-material'
import { Scrollbar } from 'react-scrollbars-custom'
import { useRouter } from 'next/router'
import MockEditorWindow from '@/components/MockEditorWindow'


export default function Home() {
  const theme = useTheme()
  const session = useSession()
  const router = useRouter()
  const [accountHovered, setAccountHovered] = React.useState(false);

  const iconDivStyle = (isHovering = false) => {
    const hoverBG = (isHovering) => isHovering ? theme.palette.background.paper : theme.palette.background.default;
    return {
      minWidth: "50px",
      height: "50px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      color: theme.palette.text.primary,
    }
  };

  const collapseStyle = (isHovering = false) => {
    const hoverBG = (isHovering) => isHovering ? theme.palette.background.paper : theme.palette.background.default;
    return {
      color: theme.palette.text.primary,
      height: '50px',
      position: "relative",
    }
  };

  return (
    <>
      <Head>
        <title>Webbie - Web IDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* This is a really really cool trick https://css-tricks.com/emoji-as-a-favicon/ */}
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕸️</text></svg>"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Teko&display=swap" rel="stylesheet" />
      </Head>
      <style>
        {`
          @keyframes rotate-text {
            0% { transform: rotateY(0deg); }
            25% { transform: rotateY(90deg); }
            50% { transform: rotateY(180deg); }
            75% { transform: rotateY(270deg); }
            100% { transform: rotateY(360deg); }
          }
        `}
      </style>

      <Scrollbar
        noScrollX
        style={{
          minHeight: '100vh',
          minWidth: '100vw',
          backgroundColor: theme.palette.background.default,
        }} >
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-start',
          alignItems: 'center',
          width: "100%",
          height: "100%",
        }}>

          <div
            id='top'
            style={{
              // backgroundColor: "#0000FF33",
              width: "100%",
              height: "100vh",
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-evenly',
              alignItems: 'center',
            }}>
            {/* Top bar start ------------------------------------ */}
            <div style={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '1rem 2rem',
              width: 'calc(100% - 4rem)',
              height: '60px',
              position: 'absolute',
              top: 0,
            }}>
              <div>
                <Typography variant='h4' style={{
                  fontFamily: 'Teko',
                  color: theme.palette.text.primary,
                  marginLeft: '1rem',
                }}>
                  Web
                  <span style={{
                    color: theme.palette.primary.main,
                  }}>
                    <span style={{
                      display: "inline-block",
                      animation: "rotate-text 8s infinite",
                      transformOrigin: "50% 50%",
                    }}>
                      bi
                    </span>
                    e
                  </span>
                </Typography>
              </div>
              <div style={{
                flexGrow: 1,
                display: 'flex',
                flexDirection: 'row',
                justifyContent: 'center',
                alignItems: 'center',
                color: theme.palette.text.primary,
                // fontSize: '2rem',
                gap: '2rem',
              }}>
                <Typography variant='body2'
                  onClick={() => window.location.href = "#TechStack"}
                  sx={{
                    color: theme.palette.text.primary,
                    cursor: 'pointer',
                    transition: '0.2s ease-in-out',
                    "&:hover": {
                      color: theme.palette.primary.main
                    }
                  }}>
                  Tech Stack
                </Typography>

                <Typography variant='body2'
                  onClick={() => window.location.href = "#Frameworks"}
                  sx={{
                    color: theme.palette.text.primary,
                    cursor: 'pointer',
                    transition: '0.2s ease-in-out',
                    "&:hover": {
                      color: theme.palette.primary.main
                    }
                  }}>
                  Frameworks
                </Typography>

                <Typography variant='body2'
                  onClick={() => window.location.href = "/editor/326ebf85-b329-41da-ad85-a1365e719273"}
                  sx={{
                    color: theme.palette.text.primary,
                    cursor: 'pointer',
                    transition: '0.2s ease-in-out',
                    "&:hover": {
                      color: theme.palette.primary.main
                    }
                  }}>
                  Try the demo
                </Typography>
              </div>
              <div>
                <Button
                  variant='filled'
                  color='primary'
                  style={{
                    backgroundColor: theme.palette.primary.main,
                    marginRight: '1rem',
                  }}
                  onClick={() => router.push("/access")}>
                  Sign In
                </Button>
              </div>
            </div>
            {/* Top bar end ------------------------------------ */}
            <div style={{
              maxWidth: '50%',
            }}>
              <Typography variant='h1' style={{
                fontFamily: 'Teko',
                color: theme.palette.text.primary,
                lineHeight: '5.5rem',
                width: '450px'
              }}>
                <span style={{ color: theme.palette.primary.main }}>
                  {"Develop "}
                </span>
                the web <br />
                from the
                <span style={{ color: theme.palette.primary.main }}>
                  {" web"}
                </span>
              </Typography>
              <Typography variant='h6' style={{
                color: theme.palette.text.primary,
                width: '450px',

              }}>
                Webbie is a web IDE that lets you develop and share web projects from your browser.
              </Typography>
              <Button variant='filled' color='primary'
                onClick={() => window.location.href = "/editor/326ebf85-b329-41da-ad85-a1365e719273"}
                style={{
                  backgroundColor: theme.palette.primary.main,
                  marginTop: '1rem',
                }}>
                Try the demo
              </Button>
            </div>
            {/* Mini Editor inside Mock Window */}
            <MockEditorWindow />
          </div>
          <div
            id="TechStack"
            style={{
              backgroundColor: "#FF000033",
              width: "100%",
              height: "70vh",
            }}></div>
          <div
            id="Frameworks"
            style={{
              backgroundColor: "#00FF0033",
              width: "100%",
              height: "33vh",
            }}></div>
          <div
            id="TryTheDemo"
            style={{
              backgroundColor: "#FF00FF33",
              width: "100%",
              height: "70vh",
            }}></div>
          <div
            id='Footer'
            onClick={() => window.location.href = "#top"}
            style={{
              backgroundColor: "#FFFFFF33",
              width: "100%",
              height: "30vh",
            }}></div>
        </div>
      </Scrollbar >

    </>
  )
}
